### ISSUE TITLE
extra space warning when used before remark-lint

### ISSUE THREAD

**Issue by keegoid** [eush77/remark-normalize-headings#1]
I've been testing `normalize-headings` with `lint`.

This produces a warning about an extra space:

``` bash
remark nh.md --use "normalize-headings" --use "lint"
```

This doesn't produce a warning about an extra space:

``` bash
remark nh.md --use "lint" --use "normalize-headings"
```

I assume this is because `normalize-headings` is not finished when `lint` starts checking the markdown? I'm not sure what's causing this erroneous warning. The output looks correct.

I prefer to run `normalize-headings` along with other remark plugins that normalize and modify markdown before checking everything over with `lint`. 

See attached example file.
[nh.md.zip](https://github.com/eush77/remark-normalize-headings/files/256759/nh.md.zip)

**Comment by wooorm** [comment]
Sorry nobody got back to you! 😬 

This issue has been stale for a while, so I’m closing it, but feel free to open a new one or chat on remark’s Gitter if this is still a problem!
